# Author: Anukool Purohit
### Nueral Network Practice

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

### Helper Functions

##### Relu Function

In [36]:
def relu(Z):
    A = (Z>0)*Z
    cache = Z
    return A, cache

In [37]:
Z = np.random.randn(5,1)
print("Z:  ")
print(Z)
print("Relu: ")
A, cache = relu(Z)
print(A)
print(Z.shape == A.shape)
print(cache)

Z:  
[[0.89273898]
 [1.97773187]
 [1.21019472]
 [0.00645692]
 [1.07894589]]
Relu: 
[[0.89273898]
 [1.97773187]
 [1.21019472]
 [0.00645692]
 [1.07894589]]
True
[[0.89273898]
 [1.97773187]
 [1.21019472]
 [0.00645692]
 [1.07894589]]


##### Sigmoid Function

In [38]:
def sigmoid(Z):
    A = 1 / (1 + np.exp(-1 * Z))
    assert Z.shape == A.shape
    cache = Z
    return A, cache

In [39]:
eg = np.random.randn(5,1)
print("E.g:  ")
print(eg)
print("Sig: ")
sig, cache = sigmoid(eg)
print(sig)
print(eg.shape == sig.shape)
print(cache)

E.g:  
[[ 0.68710827]
 [-0.19562406]
 [ 0.45331991]
 [ 0.03963324]
 [-0.15287954]]
Sig: 
[[0.66532334]
 [0.45124936]
 [0.61142828]
 [0.50990701]
 [0.46185438]]
True
[[ 0.68710827]
 [-0.19562406]
 [ 0.45331991]
 [ 0.03963324]
 [-0.15287954]]


## Functions for NN arch

In [5]:
def initialize_parameters(layer_dims):
    parameters = {}
    L = len(layer_dims)
    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        assert parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1])
        assert parameters['b' + str(l)].shape == (layer_dims[l], 1)
    return parameters

In [10]:
parameters = initialize_parameters([5,4,2])
print(parameters['W1'])
print(parameters['b1'])

[[ 0.00835939  0.00582569 -0.00090903 -0.00398713  0.00779038]
 [-0.00384187  0.00544981  0.00173918  0.00735423 -0.00269867]
 [ 0.01041535 -0.01844487 -0.00036681  0.00692515  0.00263025]
 [-0.00424285 -0.0170494   0.02295466  0.00876038  0.00722577]]
[[0.]
 [0.]
 [0.]
 [0.]]


#### Forward pass

In [11]:
def linear_forward(A, W, b):
    Z = np.dot(W, A) + b
    
    assert Z.shape == (W.shape[0], A.shape[1])
    cache = (A, W, b)
    return Z, cache

In [21]:
parameters = initialize_parameters([3,4,5])
A = np.random.randn(3,1)
print("A: ")
print(A)
W = parameters['W1']
b = parameters['b1']
Z, cache = linear_forward(A, W, b)
print("Z: ")
print(Z)
print("Cache: ")
print("    A: ")
print((cache[0]))
print("    W: ")
print((cache[1]))
print("    b: ")
print((cache[2]))

A: 
[[0.74264093]
 [0.3047762 ]
 [1.09733093]]
Z: 
[[-0.00731285]
 [ 0.01059523]
 [ 0.0060792 ]
 [ 0.01162781]]
Cache: 
    A: 
[[0.74264093]
 [0.3047762 ]
 [1.09733093]]
    W: 
[[-0.01493329  0.0030884   0.00258441]
 [ 0.00819689 -0.00895411  0.00659499]
 [ 0.0010678  -0.00458897  0.00609189]
 [ 0.00877385  0.00438182  0.00344155]]
    b: 
[[0.]
 [0.]
 [0.]
 [0.]]


In [40]:
def linear_activation_forward(A_prev, W, b, activation):
    if activation == 'relu':
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
    elif activation == 'sigmoid':
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
    assert A.shape == (W.shape[0], A_prev.shape[1])
    cache = (linear_cache, activation_cache)
    return A, cache
        

In [47]:
parameters = initialize_parameters([3,4,5])
A_prev = np.random.randn(3,1)
W = parameters['W1']
b = parameters['b1']
A, cache = linear_activation_forward(A_prev, W, b, activation='relu')
print("A_prev: ")
print(A_prev)
print("Z: ")
print(cache[1])
print("A: ")
print(A)
print("Cache: ")
print(cache)
# print("    A: ")
# print((cache[0][0]))
# print("    W: ")
# print((cache[0][1]))
# print("    b: ")
# print((cache[0][2]))
# print("    Z: ")
# print((cache[1]))

A_prev: 
[[ 0.09280884]
 [-1.69382332]
 [ 2.80735815]]
Z: 
[[-0.02670398]
 [ 0.00836594]
 [-0.01905504]
 [ 0.00521515]]
A: 
[[-0.        ]
 [ 0.00836594]
 [-0.        ]
 [ 0.00521515]]
Cache: 
((array([[ 0.09280884],
       [-1.69382332],
       [ 2.80735815]]), array([[-0.00257981,  0.01223437, -0.00204523],
       [-0.01606265, -0.00283793,  0.00179875],
       [ 0.0137368 ,  0.00306648, -0.0053915 ],
       [-0.01302917, -0.00739671, -0.00217441]]), array([[0.],
       [0.],
       [0.],
       [0.]])), array([[-0.02670398],
       [ 0.00836594],
       [-0.01905504],
       [ 0.00521515]]))


In [48]:
def full_forward_pass(X, parameters):
    caches = []
    A = X
    L = len(parameters) // 2
    
    for l in range(1, L):
        A, cache = linear_activation_forward(A, parameters['W' + str(l)], parameters['b'+ str(l)], activation = 'relu')
        caches.append(cache)
    
    AL, cache = linear_activation_forward(A, parameters['W' + str(L)], parameters['b' + str(L)], activation = 'sigmoid')
    caches.append(cache)
    return AL, caches

In [51]:
layer_dims = [3,5,8,6,3,2]
parameters = initialize_parameters(layer_dims)
X = np.random.randn(3,1)
AL, caches = full_forward_pass(X, parameters)
print("AL:  ")
print(AL)
print("caches:")
print(caches)

AL:  
[[0.5]
 [0.5]]
caches:
[((array([[ 0.96073521],
       [-0.16074361],
       [ 2.41761043]]), array([[ 0.02629559, -0.00852992,  0.01242636],
       [ 0.00385401, -0.01057975,  0.00394378],
       [-0.00276041,  0.01463035,  0.00998712],
       [-0.01249207, -0.00131497, -0.00163189],
       [-0.01049919, -0.00855673, -0.00129313]]), array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])), array([[ 0.05667632],
       [ 0.01493783],
       [ 0.0191412 ],
       [-0.01573548],
       [-0.01183779]])), ((array([[ 0.05667632],
       [ 0.01493783],
       [ 0.0191412 ],
       [-0.        ],
       [-0.        ]]), array([[ 0.00406451, -0.00544831, -0.0105896 , -0.01776958, -0.01007817],
       [ 0.00966627, -0.02335288,  0.0114844 , -0.01174214,  0.00215076],
       [ 0.00814701, -0.00477832, -0.00481156, -0.00818461, -0.00068055],
       [ 0.00502993,  0.00202496,  0.00890821,  0.00672906, -0.00145146],
       [-0.00495215, -0.01495972, -0.00446847,  0.01255817, -0.0035